GET http://localhost:6969/organizations

###
GET http://localhost:6969/organizations/62433aa5e5f993545471ef8b

###
POST http://localhost:6969/organizations
Content-Type: application/json

{
    "name": "Organization 3",
    "email": "org3@gmail.com"
}

###
PATCH  http://localhost:6969/organizations/62433aa5e5f993545471ef8b
Content-Type: application/json

{
    "members": ["180071601073"]
}

###
DELETE http://localhost:6969/organizations/6203f7b725bec00e06aad4a8